language: generic
services: docker
# Only build when I push changes to the resume.tex file in master.
branches:
  only:
  - master
install:
- docker build -t resume .
script:
- "scripts/build-pdf.sh"
after_success:
- "scripts/push.sh"
env:
  global:
  - secure: dWkOtuwBaqPvJaY5msMSuk/hkP1kUuCY5uJ9a1P7zMfGabCBYUriioszHuWHjOIXQohVUUyhMHXF+xW4amk1T+TGbdJ2HXIAJFxwr3XIfIazZND0PrYfcnBmQPf1AngTDzaw471QWo2cDjUnBt1nniX0KqxiWtAD6po7JUi9090QKKV+mJEhdcPsR5yOOTOVQNLTaJjksXt68Y4xzP8Y3/BfVacJU0gKbqk/A78Hpy1r1v1PotRhiPGS6/7hV2WUhcAPdrb9u2hhYrVoZBsGctEsiXflQUpDxY53sdyeZOe6gQopUI4o8XcMmINx3Zr+WioKIaNqvm9Bm/q36IQBltLDbYSnYrksn7jkw82u+0wf5evF/q6rP8d4ID0HgJW3lMKhL2Uq+hMDyGSC3/vn4p85GE0hZ1JCMznq2knwL8xO0ObuXlWemRhTWMoLiM7x6FNOxN7s29WaOadSJam12gTfogwM7snBFwrCV2I777BrMH+p31E/qUxM53etNkmZjq+JevjmwFxOGl4aJw5e2YAorsEV2ISF76hSnzMX4NPBammmThHCeg05/CwQIsxx/ONDqzOk/CiXa1yWfvwYwo+VwRl2EG/1Ccb6BtB6J1khpA2ORilig8SR8NYK2j5N7TyzYnRYkatHtWGO5B3oX5baDGMBvLJGs+p8MXSbmm0=
